### ISSUE TITLE
Handle multiple requests to the same endpoint with different results

### ISSUE THREAD

**Issue by alaney** [oreillymedia/cypress-playback#128]
**Is your feature request related to a problem? Please describe.**
Yes. In my test case, I am sending a GET requests to an endpoint. After updating some data and saving with a POST, I make the same GET request to the same endpoint but I expect updated data to be returned. This doesn't seem to be a case that the plugin supports. It appears that once the plugin has recorded a response to an endpoint it uses the same response for each addition request to that endpoint.

**Describe the solution you'd like**
I would like the plugin to understand that the response to each GET request may not result in the same data. So that the UI updates in an expected manner when using the playback file.

**Additional context**
Here is a short reproduction of my issue.
**NOTE:** You will need to create a new API key and replace it in the URL `endpoint` variables. You can create a new API key at https://crudcrud.com

In the example below, you can host the index.html page locally and open it in a browser. When you open it you can click `GET` to retrieve information and `POST` to update data.

The test first clicks `GET`, the `POST`, then `GET` again. The test passes when running against the live backend, but after recording a playback file the test will fail. This is because only one `GET` request is recorded.

Cypress Test
```javascript
const endpoint = 'https://crudcrud.com/api/e3e5cd900963487b8a5f0e1e1ff5b483/example';

describe('Playback', () => {
  beforeEach(() => {
    cy.playback('GET', endpoint, { toBeCalledAtLeast: 2 });
    cy.playback('POST', endpoint);
  });

  it('should record two GET requests', () => {
    cy.visit('http://localhost:8080/index.html');
    cy.findByText('GET').click();
    cy.get('#val').should('have.text', '[]');
    cy.findByText('POST').click();
    cy.wait(1000);
    cy.findByText('GET').click();
    cy.get('#val').should('contain.text', '"name":"Test"');
  });
});

```

Example App
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Playback Test</title>
</head>
<body>
  <button id="get">GET</button>
  <button id="post">POST</button>
  <pre id="val"></pre>
  <script>
    const endpoint = 'https://crudcrud.com/api/e3e5cd900963487b8a5f0e1e1ff5b483/example';
    const get = document.getElementById('get');
    get.onclick = async () => {
      const resp = await fetch(endpoint);
      const body = await resp.json();
      document.getElementById('val').innerText = JSON.stringify(body);
    } 

    const post = document.getElementById('post');
    post.onclick = async () => {
      await fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          name: "Test",
        })
      });
   
    } 
  </script>
</body>
</html>
```

**Comment by tvsbrent** [comment]
Thanks so much for the detailed example! To give you a little insight into how we store the requests, this is some pseudo-code that describes the structure:

```JavaScript
{
  "requestId1": {
    "interceptedResponseId1": {
      // Values here
    },
    "interceptedResponseId2": {
      // Values here
    },
  },
  "requestId2": {
    // More intercepted requests here.
  }
}
```

The `requestId` value is generated based on the matcher you provide in your `cy.playback` call. ([Code Here](https://github.com/oreillymedia/cypress-playback/blob/34ce37f6bc25c839ef1bdb7db5a995cf81bbf079/lib/commands/functions/getRequestMatcherId.js#L14-L21)) Despite its name, the intercepted response ID is generated from specific values in **the request made by the browser**. ([Code Here](https://github.com/oreillymedia/cypress-playback/blob/64801dc3c9269e51d50110baf29e85453ac46fc6/lib/commands/functions/getInterceptedResponseId.js#L52-L92)). If you look at that linked code, you can see we use the protocol, origin, search parameters, body, and more to create that intercepted response ID.

For a different response to be stored, the browser's request has to either match against a different "matcher" (essentially a different `cy.playback` call) or the code under test has to create a slightly different request. Would it be possible to do that in the use case you want to support? Create two `cy.playback` calls, one that is specific to the initial call and a 2nd that is specific to the 2nd call? Or could the 2nd request made by the code under test be unique in some way, perhaps adding something like a useless query parameter to it?

To get supporting this behavior without making unique matchers / response IDs, I'd have to think about that. It might involve adding code that automatically makes the `interceptedResponseId` unique or have each intercepted response be an array instead of a single entry. Requires some thought!

**Comment by alaney** [comment]
Unfortunately, I cannot change the code to make this work. The example above doesn't really represent my use case. The application under test makes many requests, does some automatic refetching, and is very large. 

Just thinking out loud. If the responses were held in an array would it make sense to store them in resolved order? Then in playback mode, each time a new request is sent that matches a "matcher", you return the "next" response item in the array of responses. 

I feel like this use case applies not only to `GET`, but all other methods.

**Comment by alaney** [comment]
I took a shot at implementing a possible solution. I have not written any official tests because I wanted some feedback first. It seems to work for my use case, however, I'm not sure if it the solution needs to be backward compatible with the original playback files.

#129

**Comment by tvsbrent** [comment]
@alaney  Thanks for your contribution.

We do have a small test coverage issue in the project that I'll address. I also want to do an alpha release of the library to test in a couple of our internal projects, as there is one regression this change _may_ introduce that I wanted to test for. Unfortunately, I don't think I'll be able to get to that until early next week.
