### ISSUE TITLE
Automock only "application/json" requests?

### ISSUE THREAD

**Issue by malibagci** [oreillymedia/cypress-playback#139]
**Describe the bug**
I want to mock all `application/json` requests for my app with RegExp but when I use below it mocks every request/response included .css, .js files also.

```js
beforeEach(() => {
  cy.playback('POST', new RegExp('^/*/'), { toBeCalledAtLeast: 0 });
  cy.playback('GET', new RegExp('^/ab/*/'), { toBeCalledAtLeast: 0 });
  cy.playback('GET', new RegExp('^/search/*/'), { toBeCalledAtLeast: 0 });
});
```

Is there any way to mock only `application/json` requests/responses?

**Comment by DigTheDoug** [comment]
The library uses Cypress intercept, so instead of using a url, you could specify a more specific [route matcher](https://docs.cypress.io/api/commands/intercept#routeMatcher-RouteMatcher) if you only want certain calls to be intercepted and mocked. For example you should be able to specify only requests with `application/json` headers.

https://github.com/oreillymedia/cypress-playback?tab=readme-ov-file#url-string-glob-regexp

**Comment by malibagci** [comment]
@DigTheDoug  thanks a lot 🙏
